### PR TITLE
atrium-elixir, revamped and revitalized

### PR DESCRIPTION
**Pull request by jacobparry**
Hey guys, I know that this is a pretty huge PR, with 3,529 additions and 1,034 deletions.

Suffice it to say that it was a labor of love of mine. 

Here is basically what I did, in a nutshell:

1. Several endpoints were non-functional and have been corrected. (The categorize_and_describe_transactions endpoint is one).
2. I added several endpoints to the library which are non-existent in the original library. The merchant endpoints are a good example..
3. Several example scripts were broken. It made more sense to me to break them off into their own modules so I could wrap them with unit and integration tests. I kept the example scripts for reference. All you have to do is plug in the api_key and the client_id key and boom, you're off to the races.

4. I refactored the codebase out into individual modules, dependent on their individual contexts and made it much easier to add a new endpoint, reducing the amount of effort and code required.
5. I modified the error codes, matching them up to what is the online documentation better, and in fact thanks to this library I was able to report a bug to you, which I did in our Slack channel with you.

### CODE REVIEW

**Comment by jacobparry** [comment]
Hmm I am not familiar with Travis CI. Is there an easy way to see why it failed? I didn't modify anything with it.

**Comment by jacobparry** [comment]
Ahh, I think I know why. https://travis-ci.org/mxenabled/atrium-elixir/jobs/597847369

I didn't want to push a commit with an API and client_id key in it, so the tests are failing.

**Comment by jacobparry** [comment]
Here is a record of the discussion so far (copied from Slack)

Steve Newell 4:21 PM
@Jacob Parry Thanks for the elixir PR.  At first glance the code looks great!  The concern with the failing spec is twofold.  First, the failures could be masking more serious issues, and secondly, the “round trip” of the requests.  Typically we like to keep the tests self contained, meaning, we don’t like tests to make actual HTTP requests.  There are a number of reasons not to do  that; I’m happy to discuss offline, if you’d like (DM me)
How would you feel about mocking the actual requests, to remove the network traffic from the tests?

Jacob Parry 4:23 PM
I can mock the tests, easy enough. That would solve the failing tests in your Travis CI pipeline. (I knew that it was there, but I didn't know how much it did)

Steve Newell 4:24 PM
Perfect.  Once that’s done, if you will @ me on the PR, I’ll take a closer look, and we’ll get it moving!  Thanks again for your help and interest!

Jacob Parry 4:24 PM
Sounds great :thumbsup:
However, when you mock everything you test nothing. Want me to provide a way where you can run the tests and actually make the requests to make sure they are working, but default it to the mocks?

Steve Newell 4:29 PM
The test suite is testing the actual API code, meaning, given this mocked response, when I make the following request, I process it correctly.  If the goal is to show workflow, we typically prefer to remove that from the test suite and place it in an examples folder.
The intention of specs is no to ensure that the actual API endpoints on our side are returning the expected data, rather that the code in the library is correct.
Does that make sense?

Jacob Parry 4:31 PM
:thumbsup:

Jacob Parry 4:37 PM
I mean, you do run the risk of the examples becoming outdated, just like they did with this last iteration. Even with the unit tests, I had to update a few of the expected responses since I first made them recently because your endpoints had already returned something slightly different. It all depends on what your strategy is and how you want to deal with it. In the end, I'll do whatever your acceptance criteria is, since it is your lib after all :slightly_smiling_face:

Steve Newell 4:38 PM
Agreed.  There is always a risk that the code will “stale”.  However, we really need those tests to pass, before we can consider merging the code.

Jacob Parry 4:40 PM
Absolutely, I wouldn't dream of merging it without them.
I'll ping you when its done

**Comment by jacobparry** [comment]
@newellista All the checks are passing. 

I marked the unit tests as sandbox tests, which will not run unless run specifically with `mix test --only sandbox`.

The reason why I did this is 

1. The examples folder still exists and has all of the existing calls in them and can be used as reference, but debugging those modules are much less efficient.

2. The unit tests will now only be run when specifically requested to, which provides an excellent way to debug the state of all the api calls and what is expected to return.

3. Having the unit tests only run when requested does what you wanted, essentially providing a "mocked" system which an be used as an object reference.

**Comment by jacobparry** [comment]
@newellista I finally resolved the readme typo. Feel free to look at things again 👍

**Comment by newellista** [comment]
:shipit:

**Pull request merged**
